#!/usr/bin/env python3
"""Regenerate docs/BACKGROUNDS_BY_BIRTH.md from races.json.

The document is a flat view of which backgrounds each birth may actually roll,
which is decided by `available_races` — an empty list means universal. It is
not `typical_backgrounds`: that field is documentation for the review docs and
is not read by KarmaSystem.select_random_background().

The file was hand-maintained and had drifted (it claimed 94 backgrounds when
there were 137). Run this after any birth or background edit:

    python3 tools/export_backgrounds_by_birth.py
"""
import json
import os
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "BACKGROUNDS_BY_BIRTH.md")


def records(d):
    return {k: v for k, v in d.items() if not k.startswith("_") and isinstance(v, dict)}


def skills_of(bg):
    return ", ".join(f"{k} {v}" for k, v in bg.get("starting_skills", {}).items())


def main():
    with open(os.path.join(ROOT, "resources/data/races.json"), encoding="utf-8") as fh:
        data = json.load(fh)
    races = records(data["races"])
    bgs = records(data["backgrounds"])

    universal = {k: v for k, v in bgs.items() if not v.get("available_races")}
    restricted = {k: v for k, v in bgs.items() if v.get("available_races")}

    # How many backgrounds name each birth, so the starved ones are visible.
    own = defaultdict(int)
    for bg in restricted.values():
        for birth in bg["available_races"]:
            own[birth] += 1
    starved = sorted(b for b in races if own[b] == 0)

    L = ["# Backgrounds by birth", ""]
    L.append("*Generated by `tools/export_backgrounds_by_birth.py` — do not hand-edit.*")
    L.append("")
    L.append(f"{len(bgs)} backgrounds. **{len(universal)} are universal** — any birth may "
             "take them.")
    L.append("The rest name specific births and are listed below.")
    L.append("")
    L.append("Universal is the default: a background with an empty `available_races` is open "
             "to")
    L.append("everyone, so births added later inherit it automatically rather than being "
             "silently starved.")
    L.append("")
    L.append("Note this is the list the roll actually uses. A birth's `typical_backgrounds` "
             "is")
    L.append("prose documentation for the review documents and does not narrow the roll.")
    L.append("")

    L.append(f"## Universal ({len(universal)})")
    L.append("")
    L.append("| background | skills |")
    L.append("|---|---|")
    for bid in sorted(universal, key=lambda b: universal[b].get("name", b)):
        bg = universal[bid]
        L.append(f"| **{bg.get('name', bid)}** `{bid}` | {skills_of(bg)} |")
    L.append("")

    L.append(f"## Restricted ({len(restricted)})")
    L.append("")
    L.append("| background | births | realms | skills |")
    L.append("|---|---|---|---|")
    for bid in sorted(restricted, key=lambda b: (-len(restricted[b]["available_races"]),
                                                 restricted[b].get("name", b))):
        bg = restricted[bid]
        births = bg["available_races"]
        realms = sorted({races[b]["realm"] for b in births if b in races})
        shown = ", ".join(births[:6]) + (" …" if len(births) > 6 else "")
        label = f"{len(births)}: {shown}" if len(births) > 6 else shown
        L.append(f"| **{bg.get('name', bid)}** `{bid}` | {label} | {', '.join(realms)} "
                 f"| {skills_of(bg)} |")
    L.append("")

    L.append(f"## Births with no background of their own ({len(starved)})")
    L.append("")
    L.append("Every one of these can take the universal backgrounds, but none is written for")
    L.append("it specifically.")
    L.append("")
    for b in starved:
        L.append(f"- `{b}` ({races[b]['realm']})")
    L.append("")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print(f"wrote docs/BACKGROUNDS_BY_BIRTH.md  ({len(bgs)} backgrounds, "
          f"{len(universal)} universal, {len(starved)} births with none of their own)")


if __name__ == "__main__":
    main()
